export const components = [
  {
    name: "MivamaProvider",
    slug: "provider",
    source: "src/components/mivama-provider.tsx",
    category: "provider",
    status: "stable",
    client: true,
    interactive: false,
  },
  {
    name: "Alert",
    slug: "alert",
    source: "src/components/ui/alert.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "AspectRatio",
    slug: "aspect-ratio",
    source: "src/components/ui/aspect-ratio.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Attachment",
    slug: "attachment",
    source: "src/components/ui/attachment.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Badge",
    slug: "badge",
    source: "src/components/ui/badge.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "BentoGrid",
    slug: "bento-grid",
    source: "src/components/ui/bento-grid.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Breadcrumb",
    slug: "breadcrumb",
    source: "src/components/ui/breadcrumb.tsx",
    category: "navigation",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Bubble",
    slug: "bubble",
    source: "src/components/ui/bubble.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Button",
    slug: "button",
    source: "src/components/ui/button.tsx",
    category: "action",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "ButtonGroup",
    slug: "button-group",
    source: "src/components/ui/button-group.tsx",
    category: "action",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Calendar",
    slug: "calendar",
    source: "src/components/ui/calendar.tsx",
    category: "form",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Card",
    slug: "card",
    source: "src/components/ui/card.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Carousel",
    slug: "carousel",
    source: "src/components/ui/carousel.tsx",
    category: "layout",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Checkbox",
    slug: "checkbox",
    source: "src/components/ui/checkbox.tsx",
    category: "form",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Choice",
    slug: "choice",
    source: "src/components/ui/choice.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Combobox",
    slug: "combobox",
    source: "src/components/ui/combobox.tsx",
    category: "form",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Command",
    slug: "command",
    source: "src/components/ui/command.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Container",
    slug: "container",
    source: "src/components/ui/container.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "ContextMenu",
    slug: "context-menu",
    source: "src/components/ui/context-menu.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "DatePicker",
    slug: "date-picker",
    source: "src/components/ui/date-picker.tsx",
    category: "form",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Dialog",
    slug: "dialog",
    source: "src/components/ui/dialog.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Direction",
    slug: "direction",
    source: "src/components/ui/direction.tsx",
    category: "provider",
    status: "stable",
    client: true,
    interactive: false,
  },
  {
    name: "Drawer",
    slug: "drawer",
    source: "src/components/ui/drawer.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "EditorialGrid",
    slug: "editorial-grid",
    source: "src/components/ui/editorial-grid.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Empty",
    slug: "empty",
    source: "src/components/ui/empty.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Field",
    slug: "field",
    source: "src/components/ui/field.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "HoverCard",
    slug: "hover-card",
    source: "src/components/ui/hover-card.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Input",
    slug: "input",
    source: "src/components/ui/input.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "InputGroup",
    slug: "input-group",
    source: "src/components/ui/input-group.tsx",
    category: "form",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "InputOTP",
    slug: "input-otp",
    source: "src/components/ui/input-otp.tsx",
    category: "form",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Item",
    slug: "item",
    source: "src/components/ui/item.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Kbd",
    slug: "kbd",
    source: "src/components/ui/kbd.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Label",
    slug: "label",
    source: "src/components/ui/label.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Marker",
    slug: "marker",
    source: "src/components/ui/marker.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Menubar",
    slug: "menubar",
    source: "src/components/ui/menubar.tsx",
    category: "navigation",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Message",
    slug: "message",
    source: "src/components/ui/message.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "MessageScroller",
    slug: "message-scroller",
    source: "src/components/ui/message-scroller.tsx",
    category: "feedback",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "NativeSelect",
    slug: "native-select",
    source: "src/components/ui/native-select.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "NavigationMenu",
    slug: "navigation-menu",
    source: "src/components/ui/navigation-menu.tsx",
    category: "navigation",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Pagination",
    slug: "pagination",
    source: "src/components/ui/pagination.tsx",
    category: "navigation",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Progress",
    slug: "progress",
    source: "src/components/ui/progress.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "RadioGroup",
    slug: "radio-group",
    source: "src/components/ui/radio-group.tsx",
    category: "form",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "ScrollScene",
    slug: "scroll-scene",
    source: "src/components/ui/scroll-scene.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Section",
    slug: "section",
    source: "src/components/ui/section.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Select",
    slug: "select",
    source: "src/components/ui/select.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Separator",
    slug: "separator",
    source: "src/components/ui/separator.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Sheet",
    slug: "sheet",
    source: "src/components/ui/sheet.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Sidebar",
    slug: "sidebar",
    source: "src/components/ui/sidebar.tsx",
    category: "navigation",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Skeleton",
    slug: "skeleton",
    source: "src/components/ui/skeleton.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Spinner",
    slug: "spinner",
    source: "src/components/ui/spinner.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Switch",
    slug: "switch",
    source: "src/components/ui/switch.tsx",
    category: "form",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Tabs",
    slug: "tabs",
    source: "src/components/ui/tabs.tsx",
    category: "navigation",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Textarea",
    slug: "textarea",
    source: "src/components/ui/textarea.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Tooltip",
    slug: "tooltip",
    source: "src/components/ui/tooltip.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Typography",
    slug: "typography",
    source: "src/components/ui/typography.tsx",
    category: "typography",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Forms",
    slug: "forms",
    source: "src/forms.ts",
    category: "form",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "DropdownMenu",
    slug: "dropdown-menu",
    source: "src/components/ui/dropdown-menu.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Popover",
    slug: "popover",
    source: "src/components/ui/popover.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Accordion",
    slug: "accordion",
    source: "src/components/ui/accordion.tsx",
    category: "layout",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Collapsible",
    slug: "collapsible",
    source: "src/components/ui/collapsible.tsx",
    category: "layout",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Avatar",
    slug: "avatar",
    source: "src/components/ui/avatar.tsx",
    category: "feedback",
    status: "stable",
    client: true,
    interactive: false,
  },
  {
    name: "Table",
    slug: "table",
    source: "src/components/ui/table.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Toast",
    slug: "toast",
    source: "src/components/ui/toast.tsx",
    category: "feedback",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "AlertDialog",
    slug: "alert-dialog",
    source: "src/components/ui/alert-dialog.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Slider",
    slug: "slider",
    source: "src/components/ui/slider.tsx",
    category: "form",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "ScrollArea",
    slug: "scroll-area",
    source: "src/components/ui/scroll-area.tsx",
    category: "layout",
    status: "stable",
    client: true,
    interactive: false,
  },
  {
    name: "Toggle",
    slug: "toggle",
    source: "src/components/ui/toggle.tsx",
    category: "action",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "ToggleGroup",
    slug: "toggle-group",
    source: "src/components/ui/toggle-group.tsx",
    category: "action",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Resizable",
    slug: "resizable",
    source: "src/components/ui/resizable.tsx",
    category: "layout",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "DataTable",
    slug: "data-table",
    source: "src/components/ui/data-table.tsx",
    category: "layout",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Chart",
    slug: "chart",
    source: "src/components/ui/chart.tsx",
    category: "layout",
    status: "stable",
    client: true,
    interactive: true,
  },
]
