export const components = [
  {
    name: "MivamaProvider",
    slug: "provider",
    source: "src/components/mivama-provider.tsx",
    category: "provider",
    status: "stable",
    client: true,
    interactive: false,
  },
  {
    name: "Alert",
    slug: "alert",
    source: "src/components/ui/alert.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Attachment",
    slug: "attachment",
    source: "src/components/ui/attachment.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Badge",
    slug: "badge",
    source: "src/components/ui/badge.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "BentoGrid",
    slug: "bento-grid",
    source: "src/components/ui/bento-grid.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Breadcrumb",
    slug: "breadcrumb",
    source: "src/components/ui/breadcrumb.tsx",
    category: "navigation",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Button",
    slug: "button",
    source: "src/components/ui/button.tsx",
    category: "action",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Card",
    slug: "card",
    source: "src/components/ui/card.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Choice",
    slug: "choice",
    source: "src/components/ui/choice.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Container",
    slug: "container",
    source: "src/components/ui/container.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Dialog",
    slug: "dialog",
    source: "src/components/ui/dialog.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "EditorialGrid",
    slug: "editorial-grid",
    source: "src/components/ui/editorial-grid.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Empty",
    slug: "empty",
    source: "src/components/ui/empty.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Field",
    slug: "field",
    source: "src/components/ui/field.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Input",
    slug: "input",
    source: "src/components/ui/input.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Message",
    slug: "message",
    source: "src/components/ui/message.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Pagination",
    slug: "pagination",
    source: "src/components/ui/pagination.tsx",
    category: "navigation",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Progress",
    slug: "progress",
    source: "src/components/ui/progress.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "ScrollScene",
    slug: "scroll-scene",
    source: "src/components/ui/scroll-scene.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Section",
    slug: "section",
    source: "src/components/ui/section.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Select",
    slug: "select",
    source: "src/components/ui/select.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Separator",
    slug: "separator",
    source: "src/components/ui/separator.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Sheet",
    slug: "sheet",
    source: "src/components/ui/sheet.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Sidebar",
    slug: "sidebar",
    source: "src/components/ui/sidebar.tsx",
    category: "navigation",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Skeleton",
    slug: "skeleton",
    source: "src/components/ui/skeleton.tsx",
    category: "feedback",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Switch",
    slug: "switch",
    source: "src/components/ui/switch.tsx",
    category: "form",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Tabs",
    slug: "tabs",
    source: "src/components/ui/tabs.tsx",
    category: "navigation",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Textarea",
    slug: "textarea",
    source: "src/components/ui/textarea.tsx",
    category: "form",
    status: "stable",
    client: false,
    interactive: true,
  },
  {
    name: "Tooltip",
    slug: "tooltip",
    source: "src/components/ui/tooltip.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Typography",
    slug: "typography",
    source: "src/components/ui/typography.tsx",
    category: "typography",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Forms",
    slug: "forms",
    source: "src/forms.ts",
    category: "form",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "DropdownMenu",
    slug: "dropdown-menu",
    source: "src/components/ui/dropdown-menu.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Popover",
    slug: "popover",
    source: "src/components/ui/popover.tsx",
    category: "overlay",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Accordion",
    slug: "accordion",
    source: "src/components/ui/accordion.tsx",
    category: "layout",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Collapsible",
    slug: "collapsible",
    source: "src/components/ui/collapsible.tsx",
    category: "layout",
    status: "stable",
    client: true,
    interactive: true,
  },
  {
    name: "Avatar",
    slug: "avatar",
    source: "src/components/ui/avatar.tsx",
    category: "feedback",
    status: "stable",
    client: true,
    interactive: false,
  },
  {
    name: "Table",
    slug: "table",
    source: "src/components/ui/table.tsx",
    category: "layout",
    status: "stable",
    client: false,
    interactive: false,
  },
  {
    name: "Toast",
    slug: "toast",
    source: "src/components/ui/toast.tsx",
    category: "feedback",
    status: "stable",
    client: true,
    interactive: true,
  },
]
